### ISSUE TITLE
集群支持

### ISSUE THREAD

**Issue by UDBIAWDIF** [xiaolingzi/lingorm-php#1]
东西不错，能不能支持一下集群，参考一下TP的模式，随机一台读

不过也最好考虑长驻后台的程序，比如WORKERMAN，那就要都连上，然后才随机一台读，做好超时重连

**Comment by xiaolingzi** [comment]
提交了一个版本，简单支持读写分离、多读多写，通过权重随机选择。
文档已更新：https://www.xxling.com/blog/article/3107.aspx

**Comment by xiaolingzi** [comment]
https://www.lingorm.com/cn/php/database.html
